config/routes.rb
BigData::Application.routes.draw do
  root 'uploads#index'

  resources :uploads, only: [:new, :create, :index]
end

app/models/checkout.rb
class Checkout < ActiveRecord::Base
  belongs_to :upload
  belongs_to :item
  belongs_to :merchant
  belongs_to :customer

  def total
    begin
      price = item.item_price
      purchase_count * price
    rescue
      self.destroy
    end
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :uploads, through: :checkouts
  has_many :checkouts
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :uploads, through: :checkouts
  has_many :checkouts
end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  has_many :uploads, through: :checkouts
  has_many :checkouts
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  has_many :checkouts
  has_many :customers,  through: :checkouts
  has_many :merchants,  through: :checkouts
  has_many :items,      through: :checkouts

  def total
    begin
      checkouts.inject(0) do |memo, checkout|
        memo += checkout.total
      end
    rescue
      self.destroy
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def index
    @uploads = Upload.all
  end

  def new
    @upload = Upload.new
  end

  def create
    @upload = Upload.create
    file_contents = params[:upload][:file].read
    if file_contents.present?
      upload = UploadCreationService.call(file_contents, @upload)
      redirect_to uploads_path
      flash[:notice] = "Success."
    else
      render :new
      flash[:notice] = "Sorry, there was an error. Please try again."
    end
  end

private

  def set_upload
    @data_file = Upload.find(params[:id])
  end


  def upload_params
    params.require(:upload).permit(:file, :upload, :filename)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.slim
doctype
html
  head
    title BigData by hireDave.me
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    .l-container
      = render 'layouts/shared/flash'
      = yield
    footer.l-footer
      = link_to "vite on github", 'https://github.com/woodall/data'

app/views/layouts/shared/_flash.slim
.flash
  - flash.each do |name, msg|
    = content_tag :div, msg, class: name

app/views/uploads/_upload_form.slim
= form_for @upload do |f|

  - if @upload.errors.any?
    #error_explanation
      h2
        = pluralize(@upload.errors.count, "error")
        | prohibited this data_file from being saved:
      ul
        - @upload.errors.full_messages.each do |msg|
          li= msg

  p= f.file_field :file
  p= f.submit

app/views/uploads/index.slim
.m-upload-area
  .m-uploads
    h1 Uploads
    - @uploads.each do |upload|
      - if upload.total.is_a?(Fixnum) && upload.total > 0.1
        p
          b= number_to_currency(upload.total)
          i= upload.created_at.strftime(" (%b %e)")
  .m-new-upload
    .button= link_to "Upload A File", new_upload_path

app/views/uploads/new.slim
h1 Upload a tab-separated text file
= render 'upload_form'